import 'Lang/lang.js';
import 'Base/base.js';
import 'BirdsDescription/birds-description.js';
import 'Slider/slider.js';
import 'BirdsList/birds-list.js';
import 'Player/player.js';
import 'Score/score.js';
import 'Settings/settings.js';
import 'Gallery/gallery.js';
